### ISSUE TITLE
Batch closes open fonts, unlike previous version

### ISSUE THREAD

**Issue by cjdunn** [typemytype/batchRoboFontExtension#35]
When I click "Add Open Fonts" and then "Generate" my open fonts are closed by Batch. In the previous version which worked with RF 1.8 (commit 6750671 and before) this didn't happen. 

For me this is a bug and not a feature, because many times I want to generate and keep the fonts open. There could be an option to "Close fonts after generating" if this is desired, but I don't think it's good as a default because it's unexpected. Thanks for your consideration!

**Comment by typemytype** [comment]
fixed please download manually and test

**Comment by cjdunn** [comment]
@typemytype I re-downloaded it and it's fixed for generating in the "Batch Generate" section (thanks!), but still not fixed when clicking "Generate" in the "Web Fonts" section.
Looks like webFormat/__init__.py has to be changed as well. I'll submit a PR if you want

**Comment by cjdunn** [comment]
Here's the PR: 
https://github.com/typemytype/batchRoboFontExtension/pull/36
